### ISSUE TITLE
[FEATURE] Info via Mail if system is already running or already stopped

### ISSUE THREAD

**Issue by janahockenberger** [PatrickZink/sap-start-stop-via-mail#1]
### Describe the solution you'd like

Currently the solution just writes an email as soon as a system is being started or stopped.
In case two people sequentially send the start or stop mail, a mail should be sent that the system is already running/stopped.

**Comment by PatrickZink** [comment]
Thank you for the feature request.

The feature has been implemented. If an attempt is made to start or stop the system via email and it is already in the desired state, an SNS notification will be generated. For example, "The system S4H is already running at accountname."

By sending an email with the subject "Status SID", the current status of the system will be notified via SNS.
